### ISSUE TITLE
1.2 Update

### ISSUE THREAD

**Issue by dtoxic47** [Mihara/SensiblePumps#3]
Update Please

**Comment by linuxgurugamer** [comment]
I'm forking this, will be available in a day or so

**Comment by Mihara** [comment]
@linuxgurugamer:
I don't have much time for KSP these days, I could just transfer the repo to you entirely if you like.

**Comment by linuxgurugamer** [comment]
If you want, I already did a fork, so I have no idea what would  happen on github when you transfer me the head.  Would be interesting.

**Comment by Mihara** [comment]
Me neither, to be honest, probably nothing good. :)
